export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const GET_ITEM = "GET_ITEM"

export const GET_MATERIALS = 'GET_MATERIALS';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const FAILED_ITEMS = 'FAILED_ITEMS';

export const NOT_LOGGEDIN = 'NOT_LOGGEDIN';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_TOKEN = 'LOGIN_TOKEN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const AUTH_LOADING = "AUTH_LOADING";

export const NOT_ALLOWED ="NOT_ALLOWED"
export const NOT_FOUND = "NOT_FOUND"
export const CUSTOMERS_LOADING ="CUSTOMERS_LOADING"
export const MATERIALS_LOADING = "MATERIALS_LOADING"

export const ITEM_ERROR = "ITEM_ERROR"
export const CLEAR_ADDED = "CLEAR_ADDED"

export const PROFILE = "PROFILE"
export const PROFILE_FAIL = "PROFILE_FAIL"

export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const UPDATE_ERROR = "UPDATE_ERROR"
export const GET_PERIODS = "GET_PERIODS"
export const PERIODS_LOADING = "PERIODS_LOADING"
export const FAILED_PERIODS = "FAILED_PERIODS"
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN"
export const LOAD_FAIL = "LOAD_FAIL"
export const CALENDAR_LOADING = "CALENDAR_LOADING"
export const GET_ITEMS_DATE = "GET_ITEMS_DATE"
// clients
export const GET_CLIENT_PERIODS = "GET_CLIENT_PERIODS"
export const CLIENT_LOADING = "CLIENT_LOADING"

export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const GET_CUSTOMER_ITEMS = "GET_CUSTOMER_ITEMS"

export const CLEAR_ITEM = "CLEAR_ITEM"